### ISSUE TITLE
OR Searching Instead of AND Searching

### ISSUE THREAD

**Issue by Bha-Gu** [WaterKH/WayfinderProjectAPI#10]
**Describe the bug**

Searching luxu and ventus give scenes without luxu.
Many seens are not labled with xigbar/braig in them
yet they still come in search

**Screenshots**

![Screenshot from 2022-10-22 07-25-23](https://user-images.githubusercontent.com/67630917/197311517-ef9bc910-5070-4418-ac50-0ba68087029d.png)

**Correction**

**Additional context**
i was initialy hoping luxu whould also track Xigbar which it seems to have done

**Comment by WaterKH** [comment]
The problem is it's getting every scene with a combination of these two, as opposed to getting just the scenes they are in together.

**Comment by Bha-Gu** [comment]
Or searching is happening again.

![image](https://user-images.githubusercontent.com/67630917/216541616-702ef1a8-90f1-4569-a952-5e19f8de9210.png)

I tested it with/without alias config and it always does or searching.
I have not done exhaustive test.
maybe it happens if first search is an empty search.
