### ISSUE TITLE
Several Dark Road scenes link to outdated versions

### ISSUE THREAD

**Issue by lucidcrystal** [WaterKH/WayfinderProjectAPI#106]
Several cutscenes from Dark Road were changed with version 5.0.1, however the Wayfinder Project still links to the 5.0.0 versions of them. The scenes that were changed are:

A Recurring Dream (updated version: https://www.youtube.com/watch?v=58Dwz-YGR4U&list=PLPCJnwphQDQeeHwWywi0r1w-GMn6Z9-Mz&index=8)

Dark Emotions (updated version: https://www.youtube.com/watch?v=nt7T58DHkDE&list=PLPCJnwphQDQeeHwWywi0r1w-GMn6Z9-Mz&index=50)

A Worthy Heart (updated version: https://www.youtube.com/watch?v=gGwDWv29k8E&list=PLPCJnwphQDQeeHwWywi0r1w-GMn6Z9-Mz&index=61)

Reunited (updated version: https://www.youtube.com/watch?v=FkXlz8gYa5Q&list=PLPCJnwphQDQeeHwWywi0r1w-GMn6Z9-Mz&index=62)

Two Kinds of People (updated version: https://www.youtube.com/watch?v=AA2sh_5x2oc&list=PLPCJnwphQDQeeHwWywi0r1w-GMn6Z9-Mz&index=92)

Child of Destiny (updated version: https://www.youtube.com/watch?v=4Fm2diD49hs&list=PLPCJnwphQDQeeHwWywi0r1w-GMn6Z9-Mz&index=95)

Also, the updates to Dark Emotions, A Worthy Heart, Reunited, and Child of Destiny included dialogue changes so the transcripts for those scenes should be updated as well.

**Comment by WaterKH** [comment]
Thank you so much, this was very helpful!
