### ISSUE TITLE
Follow-up on previous issue

### ISSUE THREAD

**Issue by RegularPat** [WaterKH/WayfinderProjectAPI#119]
There's still somethin' weird going on with KH2 scene "Cosmic Razzle-Dazzle" (I was going to pull it again for my current project lmao) the script is still missing and now the video doesn't actually link anywhere 
![image](https://user-images.githubusercontent.com/86783977/236656635-6060d5ed-ccd5-46a0-b0d3-cf1a822315d5.png)

**Comment by WaterKH** [comment]
This issue was caused by me updating the Link to "Cosmic Razzle Dazzle" instead of the Name - This caused the dialogue to still not be updated and the link to now redirect incorrectly. This is fixed now.
