### ISSUE TITLE
Follow-up to text bubbles/interactions

### ISSUE THREAD

**Issue by RegularPat** [WaterKH/WayfinderProjectAPI#133]
copy-pasted from Discord:

Just following up on the topic of the text scenes-- I think we can pretty much just sort the ones that actually play out like cutscenes into the scenes section (eg. meeting the PoH in the Castle Chapel, talking to the FF characters outside the Keyhole, and they can just be at the end of the list like all of the summons/alt scenes in KH1 are) but the instances where you have to purposefully talk to characters on the field (eg. Kairi giving hints for the raft stuff or Aerith in the library) should be treated as "interactions," and I can mark these all accordingly on the doc I'm using to keep track of all this

**Comment by WaterKH** [comment]
Do you have an update on this? If you could DM me the specifications, I can start modeling this.
