### ISSUE TITLE
Radiant Garden/Days Miscategorization

### ISSUE THREAD

**Issue by Chaineh** [WaterKH/WayfinderProjectAPI#145]
![Screenshot_9](https://github.com/WaterKH/WayfinderProjectAPI/assets/90538666/36a06bff-bbb1-4d39-b248-c8e9cf1ff74c)
**Describe the bug**
Under the cutscene "Opening" for Kingdom Hearts 358/2 Days, it is miscategorized in "Radiant Garden", when it should be under "Hollow Bastion" since all the scenes in the opening depict the world pre-Tron.

**Additional context**
This is also the only cutscene under the label "Radiant Garden" for "Kingdom Hearts 358/2 Days", so I'm not sure if it updates automatically, but once the scene is corrected, Days shouldn't have the "Radiant Garden" filter as an option anymore. Also, thanks for everything you do Water! :3

**Comment by WaterKH** [comment]
Thank you Chaineh!!
