### ISSUE TITLE
Missing Videos (Sora Meets Julius/Sora Defeats Julius/Riku Meets Julius/Riku Defeats Julius)

### ISSUE THREAD

**Issue by BriskApollo** [WaterKH/WayfinderProjectAPI#151]
![image](https://github.com/WaterKH/WayfinderProjectAPI/assets/119282948/33d9c163-0791-4c6f-9618-990a768e83ed)

![image](https://github.com/WaterKH/WayfinderProjectAPI/assets/119282948/824a2868-7c87-4e9a-b386-9f9fbe453954)

![image](https://github.com/WaterKH/WayfinderProjectAPI/assets/119282948/8d1555bc-319d-4bac-b661-ae25328ca185)

![image](https://github.com/WaterKH/WayfinderProjectAPI/assets/119282948/3966eabd-06ae-49fd-be80-2e0a15c70653)

**Comment by WaterKH** [comment]
I haven't been given links to these from The Wayfinder Project, so these are left blank for now - It's possible @RegularPat would be able to provide these or someone from his group

**Comment by BriskApollo** [comment]
I found two full videos that contain the scenes from other channels and edited them for the video I'm working on. Would you like me to send you the individual clips? I'm not sure if the "help wanted" button means you're asking me for help or not lol

**Comment by WaterKH** [comment]
I think I'll leave this for Pat to get onto the Database YT Channel, but thank you! The "help wanted" is to signify that this needs community action, either by Pat or others ❤️ Thank you for the scripts for the Episodes!

**Comment by WaterKH** [comment]
If you wanted to provide those videos actually @BriskApollo I think it doesn't necessarily need to be hosted on the YT Database channel 👍 That way I can update and close this

**Comment by BriskApollo** [comment]
MY BAD! I'm just now seeing this!!

Here ya go:

- Sora Meets Julius: https://youtu.be/4H3MSyGRFYU
- Sora Defeats Julius: https://youtu.be/3mITQAPXfFA
- Riku Meets Julius: https://youtu.be/g1y7nMcHY8c
- Riku Defeats Julius: https://youtu.be/nY7EMMPElhk
