### ISSUE TITLE
ReCoM scene incorrectly listed as KH X scene and missing info

### ISSUE THREAD

**Issue by RegularPat** [WaterKH/WayfinderProjectAPI#170]
Scene "Friends Forever (Alternate)" is listed as a Kingdom Hearts X scene, but should be listed as KH ReCoM scene. Additionally, it needs characters and its script--

Characters: Pooh, Sora

Script--

Sora: I guess we can't go any farther. So Pooh, wasn't it more fun looking for friends together?

Pooh: Yes. Thank you. Whew...I've walked so far, I think I need a little rest. If only I had a honey pot to keep me company...

Sora: ...Well, I'd better be going.

Pooh: Where to?

Sora: To look for my friends.

Pooh: Are you sure you don't need my help?

Sora: Yeah. You should stay close to home.

Pooh: All right, Sora. I'll be sure to do the remembering for both of us.

**Comment by WaterKH** [comment]
Thank you Pat! We are already tracking in #157 so I will close this one for now
