### ISSUE TITLE
KH3 credits inclusion

### ISSUE THREAD

**Issue by Chaineh** [WaterKH/WayfinderProjectAPI#173]
**Describe the bug**
Only half of the credits are included in the scene "Another Ending" from KH3. I'm guessing this is because the second half isn't in Theater Mode? But idk if you even want to include the credits in the WFP. In the event you do, here's all the info:

**Worlds**
100 Acre Wood, Arendelle, Kingdom of Corona, Olympus, Port Royal, San Fransokyo, Toy Box, Twilight Town,

**Characters**
Anna, Baymax, Boo, Buzz, Elizabeth Swann, Elsa, Flynn Rider, Fred, Go Go, Gopher, Green Army Men, Hamm, Hercules, Honey Lemon, Hiro, Jack Sparrow, Joshamee Gibbs, Kristoff, Little Chef, Little Green Alien(s), Lumpy, Marshmellow, Maximus, Megara, Mike, Olaf, Pascal, Pegasus, Philoctes, Piglet, Pooh, Rabbit, Rapunzel, Rex, Roo, Scrooge McDuck, Sulley, Tigger, Wasabi, Will Turner, Woody,

Note: There's also unnamed Olympus, San Fransokyo, and Twilight Town NPCs

**Areas**
Agora, Alleyway, Andy's Room, Central District, Docks, Flying Dutchman, Horseshoe Island, Laugh Floor, Le Grand Bistro, Open Waters(?), Rabbit's House, Thoroughfare, Tram Common,

Note: The unnamed frozen slider area also makes an appearance, 

**Music**
[Rhapsody in Tres](https://www.youtube.com/watch?v=3qIzyqH53bM&list=PLcwpNMc641b47xABPbHEQRgwbQiud9OsO&index=120)

**Video**
[Kingdom Hearts III + Re Mind Theater Mode Scene 240- Ending](https://www.youtube.com/watch?v=gI8nIyeJfw8)

Note: Finding all this info was a collaborative effort of myself, Aimu, and Daviddaybreak.

**Comment by WaterKH** [comment]
Thank you all for coallating this information! Do you know if this is roughly the same information in the base game? Or are these different areas and characters? If they are the same, I may link them in a way, but I also don't want to confuse people if they are watching this scene and this information above is not in it. If there's missing information from the original ending though, I can move these values above into the appropriate tables. I don't want to waste the effore put into getting all this data, so I definitely want to include it if possible!

**Comment by Chaineh** [comment]
Wait I'm a fool. "Another Ending" is fine. The actual correction should be in the cutscene titled "Ending"

*Areas that need to be added: Agora, Alleyway, Andy's Room, Central District, Docks, Flying Dutchman, Horseshoe Island, Laugh Floor, Le Grand Bistro, Open Waters(?), Rabbit's House, Thoroughfare, Tram Common

*Music that needs to be added: [Rhapsody in Tres](https://www.youtube.com/watch?v=3qIzyqH53bM&list=PLcwpNMc641b47xABPbHEQRgwbQiud9OsO&index=120)

**Comment by WaterKH** [comment]
Apologies for this taking so long, but this is now complete - Thank you all for the data!
