### ISSUE TITLE
"Reunion" scenes in KHUX not displaying scripts

### ISSUE THREAD

**Issue by RegularPat** [WaterKH/WayfinderProjectAPI#180]
probably cuz of the colon in the scene name lol

affected scenes:

Reunion: Belle of the Ball
Reunion: Hero of Olympus
Reunion: For My Sweet Prince
Reunion: Curious Alice
Reunion: The Desert Oasis

**Comment by WaterKH** [comment]
I don't believe I received these in the document you provided - Are you able to point these out for me so that I can re/process?

**Comment by RegularPat** [comment]
No prob-- this should be all of 'em:
https://docs.google.com/document/d/1CIB_xldfbNrHcwrtjWEB2UUBRnXMwfC4S911G_x-FO0/edit
