### ISSUE TITLE
Patreon Supporters not showing up on the Support page

### ISSUE THREAD

**Issue by DarkImpulse12** [WaterKH/WayfinderProjectAPI#185]
Section under "Patreon Supporters" says "ERROR WITH PATREON API - Patron since UNKNOWN"

**Comment by WaterKH** [comment]
Will prioritize this

**Comment by WaterKH** [comment]
This has been resolved - The Access Token for Patreon expired, so we'll need to set a reminder to re-up this every x months. Thank you for raising this!
