### ISSUE TITLE
Textbox Cutscenes Missing

### ISSUE THREAD

**Issue by DarkImpulse12** [WaterKH/WayfinderProjectAPI#187]
**Describe the bug**
KH1 appears to be missing many textbox based cutscenes which add context to what's happening. For example Cheshire Cat's entrance is included as it's an animated cutscene, but everything Cheshire Cat says is part of textbox cutscenes so is cut and the next scene in the archive is after the card fight. Most of the small cutscenes that recap what was said in the textbox cutscenes are also cut.

**Correction**
Add the missing textbox cutscenes, although they'd probably need sourcing or recording

**Comment by WaterKH** [comment]
I believe this is captured in the "Interactions" tab in the website - Although, there was discussion of how this could be confusing... I am not sure if we have a better option right now, but we will keep this in mind. I will leave this open for now for people to leave suggestions.

Link to Interaction specified in this issue: https://wayfinderprojectkh.com/memory_archive?game=1&category=Interactions&open_row=263
