### ISSUE TITLE
Ansem tagged as Ansem the Wise throughout CoM

### ISSUE THREAD

**Issue by DarkImpulse12** [WaterKH/WayfinderProjectAPI#191]
**Describe the bug**
Ansem Seeker of Darkness is tagged as Ansem the Wise throughout CoM scenes. Also is not tagged for the voice throughout the Riku scenes in Hollow Bation

**Correction**
Tag changed as applicable and added for the disembodied voice

**Comment by WaterKH** [comment]
For this, the voice I believe is actually from Ansem the Wise, just disguised as Ansem Seeker of Darkness - This could be classified as a unique case where we want to associate either both or the disguised voice. Thoughts? @RegularPat
