### ISSUE TITLE
YouTube Channel No Longer Available

### ISSUE THREAD

**Issue by yodizzle** [WaterKH/WayfinderProjectAPI#192]
**Describe the bug**
For many of the music external links for the cutscenes of Kingdom Hearts X Back Cover, the link goes to a Youtube channel that has either Privated the video, or the Youtube channel that had the video was "terminated". Examples, Night of Fate, Scent of Silence, Friends in My Heart. I'm guessing this might affect other cutscenes from other games used too, if the same links were used.

**Comment by WaterKH** [comment]
If we can get a comprehensible list with the new link provided, this way we can update to use the alternative links - Thank you!

**Comment by Chaineh** [comment]
Looked through Back Cover, seems to be only these 5:

[Scent of Silence](https://www.youtube.com/watch?v=v9OxlksAIfA)
[Shaded Truths](https://www.youtube.com/watch?v=fx7D69fpvm0)
[Night of Fate](https://www.youtube.com/watch?v=xDkWLYFm-Nk)
[Tears of the Light](https://www.youtube.com/watch?v=L6-UY-Kf2Hs)
[Friends in My Heart](https://www.youtube.com/watch?v=_6Bu7Z9OPvA)
