### ISSUE TITLE
Unable to Discover Via Search - Round 2: Seifer vs. Vivi (Kingdom Hearts 2)

### ISSUE THREAD

**Issue by BriskApollo** [WaterKH/WayfinderProjectAPI#200]
Whenever I try to find dialogue to bring this scene up via the search bar, it doesn't come up at all.

![image](https://github.com/WaterKH/WayfinderProjectAPI/assets/119282948/0c718fbf-68f2-45fd-a99a-6af326b79d5a)

![image](https://github.com/WaterKH/WayfinderProjectAPI/assets/119282948/f9878e04-0af4-4044-b95f-128b93a04ac9)

![image](https://github.com/WaterKH/WayfinderProjectAPI/assets/119282948/bb6131c7-c9a4-4e14-97f8-f3c50afa0460)

![image](https://github.com/WaterKH/WayfinderProjectAPI/assets/119282948/4e21435b-cf8c-4cf4-985f-ce3726a8fa5c)

**Comment by WaterKH** [comment]
There was some odd behaviour between the Database correlations between scene and script for these - This has been addressed
