### ISSUE TITLE
Re:Coded "An Unexpected Bond" Music Correction

### ISSUE THREAD

**Issue by Niosa** [WaterKH/WayfinderProjectAPI#209]
**Correction**
The song used in the scene is correctly listed as "The Other Promise" but the version linked is actually the original version, not the Piano Collections version used in the scene.

[Here's a YouTube link to the Piano Collections version of the song. It should be timestamped, but if not, the game uses from 1:26 onward.](https://youtu.be/2XTfQqu6zIo?t=86)

**Additional context**
I realize this is an "UM, ACKSHUALLY" technicality thing but I also was trying to find the exact version of the song that was used in that scene since it was notably different. It's still The Other Promise and if the website isn't meant to distinguish different versions, my bad lmao

**Comment by WaterKH** [comment]
No, this is perfect! Thank you for providing the required information to make the update easy! Benefits of having this as an open project for people to make these kinds of changes

**Comment by Niosa** [comment]
You're a legend! (Though I just realized that it switches to the Piano Collections version of "Roxas" later on in the scene, I thought "The Other Promise" just transitioned to it, but no, it's a totally separate song on the album!)

In the scene, the song switches at 2:56, it's SUPER smooth. Here's the track: https://www.youtube.com/watch?v=roTSAy5QJJA

I will open a second issue if I have to I AM SO SORRY LMAO
