### ISSUE TITLE
Birth by Sleep Soundtrack YouTube Links Seem to be Broken (Videos Removed)

### ISSUE THREAD

**Issue by Niosa** [WaterKH/WayfinderProjectAPI#212]
**Describe the bug**
Most of the Birth by Sleep OST links in the Memory Archive seem to lead to removed videos. Links to contextual music from KH2, etc. still work, it's just BBS tracks.

**Additional context**
I don't know if it's all of them, but it definitely seems like it's all Birth by Sleep tracks. I imagine they must've been part of a specific playlist/from a specific uploader and they were removed en masse. Just in case, a few specific examples are:

Finding Mickey: The links to "Shaded Truths" and "Cheers for the Brave"
Three Lights: The link to "Destiny's Union"
Where The Heart Goes: "Ventus"

**Comment by WaterKH** [comment]
Hey Niosa - I can see that these are privated by the user. If you would like these updated, can you provide a list of the name and link to the new YouTube song link? You can do this in the following format:

1. {Song Name 1} - {Song YouTube Link 1}
2. {Song Name 2} - {Song YouTube Link 2}
3. etc.

**Comment by WaterKH** [comment]
Hey @Niosa - Are you able to provide a list of these so that I can update the database with the required information?

**Comment by Niosa** [comment]
Hey, sorry, I got super busy and totally forgot to follow up. I went down the complete list of scenes from Birth by Sleep and checked every song link. This should be roughly in order from that list!

1. Simple and Clean -PLANITb Remix- - https://www.youtube.com/watch?v=30ob9yBEy0o

2. Xehanort - https://www.youtube.com/watch?v=IbXVo_iookE

3. The Key of Light - https://www.youtube.com/watch?v=ksacX2f6d1c

4. Destiny's Union - https://www.youtube.com/watch?v=lYbiRit7NJ0

5. The Promised Beginning - https://www.youtube.com/watch?v=wv1zAfOiX-s

6. Future Masters - https://www.youtube.com/watch?v=dLETbYWgBY8

7. Terra - https://www.youtube.com/watch?v=Dz2nQOerSM0

8. The Rustling Forest - https://www.youtube.com/watch?v=uN_4HY_jgNI

9. The Silent Forest - https://www.youtube.com/watch?v=w7XhKdueJMQ

10. Villains of a Sort - https://www.youtube.com/watch?v=JiUDTCRwAZM

11. Risky Romp - https://www.youtube.com/watch?v=YHH7zPpXubA

12. Vim and Vigor (The current link is wrong, it directs to 'Apprehension') - https://www.youtube.com/watch?v=6ccMAXJAnPs

13. Tears of the Light - https://www.youtube.com/watch?v=L6-UY-Kf2Hs

14. Bibbidi-Bobbidi-Boo - https://www.youtube.com/watch?v=Ovfvmyal5cs

15. Castle Escapade - https://www.youtube.com/watch?v=t7_iMnJMdqI

16. Peaceful Hearts - https://www.youtube.com/watch?v=PkLSUqmoHAk

17. The Tumbling - https://www.youtube.com/watch?v=1vqkiurPauc

18. Drops of Poison - https://www.youtube.com/watch?v=JUsZCuZ7eZA

19. The Worlds - https://www.youtube.com/watch?v=ayKFEm6TJ5A

20. Ventus - https://www.youtube.com/watch?v=XBCfFl1KTzo

21. Black Garden - https://www.youtube.com/watch?v=muxGXi5OFjc

22. Radiant Garden - https://www.youtube.com/watch?v=2SGTf6219_Q

23. Innocent Times - https://www.youtube.com/watch?v=hKFXTEgZHS8

24. Unforgettable - https://www.youtube.com/watch?v=GUC29a-hf98

25. Black Powder - https://www.youtube.com/watch?v=zc4keDDJYR8

26. Up Down Adventure - https://www.youtube.com/watch?v=LjWH5D3Wlqk

27. Mickey Mouse Club March - https://www.youtube.com/watch?v=EwUhXSurJ_Y

28. Hero or Heel? - https://www.youtube.com/watch?v=PUe3IjW19Ao

29. Olympus Coliseum - https://www.youtube.com/watch?v=yruN53dZQbg

30. Shrouding Dark Cloud - https://www.youtube.com/watch?v=0Azw7-33pX8

31. Extreme Encounters - https://www.youtube.com/watch?v=AZlWNdTVbvE

32. A Date with Fate - https://www.youtube.com/watch?v=O81Wqe0A41g

33. Hau'oli, Hau'oli! - https://www.youtube.com/watch?v=b3G8YCkkcgY

34. Mákaukau? - https://www.youtube.com/watch?v=B28HvWb8bkU

35. Daydream upon Neverland - https://www.youtube.com/watch?v=hSOU5HcHlMY

36. Shaded Truths - https://www.youtube.com/watch?v=fx7D69fpvm0

37. The Key of Darkness - https://www.youtube.com/watch?v=2fCmst7IUjk

38. Beyond The Door - https://www.youtube.com/watch?v=wFgHi7iloHE

39. Enter the Darkness - https://www.youtube.com/watch?v=-T9xLU_2-5g

40. Eternal Moments - https://www.youtube.com/watch?v=xaqZSAUh5oY

41. Cheers for the Brave - https://www.youtube.com/watch?v=qgBUcKNOF1A

42. Neverland's Scherzo - https://www.youtube.com/watch?v=y7eD3-WmGTM

43. The Key - https://www.youtube.com/watch?v=737V7XHgTfY

44. Aqua - https://www.youtube.com/watch?v=qgW-kTXmjjA

45. Destiny's Force - https://www.youtube.com/watch?v=Fo2_xKJgzYk

46. Destiny Islands - https://www.youtube.com/watch?v=IkXMnezu13g

47. Another Side - https://www.youtube.com/watch?v=0GsIBxQdJ38

48. Dismiss - https://www.youtube.com/watch?v=EdKN9vWFMTQ

49. Dearly Beloved - https://www.youtube.com/watch?v=_dNipWkKWGk

**Comment by WaterKH** [comment]
Thank you so much! Implementing now!
