### ISSUE TITLE
Cutscene of the day

### ISSUE THREAD

**Issue by Capt-Blitz** [WaterKH/WayfinderProjectAPI#28]
This is just an idea I had to add some charm to the Wayfinder Project site. Feel free to ignore it if you want.

But a "Cutscene of the day" thing where a random cutscene gets pulled every day and posted up on the top could be neat.

Like I said, totally a flavor thing, and running this thing probably takes a lot of time. Just thought I would share something I thought up

**Comment by WaterKH** [comment]
This was a concept I had in mind, and I do want to do this! Thank you for letting me know other people would be interested in this as well!

**Comment by WaterKH** [comment]
Looked into using Quartz.NET for scheduling to make this also generate a tweet once a day with the cutscene of the day.

**Comment by WaterKH** [comment]
Closing this with latest commit - Adds a Cutscene of the Day and Random Cutscene Generator to the main page, as well as a tweet daily from the WFP_KH twitter: https://twitter.com/WFP_KH
