### ISSUE TITLE
Add Robed Figure to the list of characters

### ISSUE THREAD

**Issue by dasafe** [WaterKH/WayfinderProjectAPI#36]
Having Robed Figure would make it easier to find cutscenes where he shows up.
Or as in "This World Has Been Connected" in KH1 that doesn't even list Ansem as a character.

![image](https://user-images.githubusercontent.com/48550353/201478044-6b54bf04-fe53-4c24-8a12-ac41a8e65efa.png)

**Comment by WaterKH** [comment]
Please refer to #9 for progress on adding aliases.
