### ISSUE TITLE
Entries for the KH2 Summons

### ISSUE THREAD

**Issue by Capt-Blitz** [WaterKH/WayfinderProjectAPI#46]
Yes hello? I would like to make a submission to the Wayfinder Project.
The KH1 Summons have their into animations in the Wayfinder Project, and I would like to request that the KH2 Summons be included as well. I have the required videos prepared in the playlist linked below, though I understand if you say no.
(Hilariously, this would require making a new character tag for Chicken Little and only Poultry Small because every other summon shows up somewhere else)
https://youtube.com/playlist?list=PLHCDfd9aWfBNZJaqOpzKOlTD8wbjOyHYv

**Comment by WaterKH** [comment]
We can add these, just may take me a bit since I have other priorities, but thank you for this!
