### ISSUE TITLE
Issue with "Cutscene Of The Day"...I think...

### ISSUE THREAD

**Issue by Capt-Blitz** [WaterKH/WayfinderProjectAPI#54]
So I think the Cutscene Of The Day button is broken, but it might just be me. While the similar Random Cutscene button works exactly as you would expect, the CotD button just...never loads the scene. This could just be a cry for help from my computer, and it might be working fine for others. Just thought you should have this noted. 
If this is just a me issue, then great job at making that feature, have a chocolate cookie and glass of milk as a reward. (You know what, still have that cookie, you deserve it after all this)

**Comment by Capt-Blitz** [comment]
Nevermind, it fixed itself on my end. Good job, magic code.

**Comment by WaterKH** [comment]
Nah, I actually just fixed this with the latest commit, some other code was saying this wasn't properly functioning. But should be all sorted now, thank you!
