### ISSUE TITLE
Duplicated Music

### ISSUE THREAD

**Issue by Capt-Blitz** [WaterKH/WayfinderProjectAPI#72]
A previous bug that affected the track "Broken Reality" also seems to be affecting the track "Little Lovely Moments". The track is listed twice in search results, and every scene where it plays has it listed twice. 
Affected scenes are "Lauriam & Strelitzia", "Friends Once Again", "A World Outside Her Window", and "Together Forever".
![image](https://user-images.githubusercontent.com/116446650/206866569-b0e59562-9fd2-4361-8794-cb20097e5b96.png)
![image](https://user-images.githubusercontent.com/116446650/206866584-47dd5d6f-28aa-4009-9bcc-f1b627bc82ac.png)

**Comment by Capt-Blitz** [comment]
I have done some further digging and found several more tracks that suffer from the same issue. Though some maybe different tracks, these differences are not noted in the track title. (ie. the first may the original KH1 version but the second could be the 1.5 version). 

These tracks include but may not be limited to (as I may have missed some)
-Always on My Mind 
(affected scenes: "Closing The Door", "A World Restored", "Checkmate", and "KINGDOM HEARTS 3: Chapter 5")
![image](https://user-images.githubusercontent.com/116446650/206867837-f6deb10e-b905-4627-b350-550bc438a263.png)
![image](https://user-images.githubusercontent.com/116446650/206867910-fab481bc-e258-4b09-83a5-c3ed24bbb4ac.png)

-Cheers For The Brave (which is listed thrice)
(affected scenes: "Reasons", "An Important Match", "Finding Mickey", "Overnight Musketeers", and "One Final Inquiry")
![image](https://user-images.githubusercontent.com/116446650/206867958-b0e46ba8-9062-4a37-bbae-7170e8851418.png)
![image](https://user-images.githubusercontent.com/116446650/206868007-3c345b89-279d-4e84-9784-416a88642c35.png)

-Disappeared
(affected scenes: "The Unknown", "Why Do You Hate the Darkness?", and "A Grand Battle")
![image](https://user-images.githubusercontent.com/116446650/206868079-2f3ad945-2fb4-4c63-80d9-fa70b7d1c638.png)
![image](https://user-images.githubusercontent.com/116446650/206868085-edf22d99-9e48-44cb-95ff-2b5c2df48c38.png)

-Disquieting
(affected scenes: Basically half of Re:CoM and "A Replica For Roxas")
![image](https://user-images.githubusercontent.com/116446650/206868107-339e9705-c769-4d20-9589-5b956d8cfd8d.png)
![image](https://user-images.githubusercontent.com/116446650/206868157-23fb3595-99df-4c12-b682-50a0fccc5887.png)

-The 2.5 version of Friends In My Heart
(Affected scene: "Goodnight", which is oddly not in 2.5?)
![image](https://user-images.githubusercontent.com/116446650/206868176-8148a49c-30b6-452e-8605-b6cad82c27f9.png)
![image](https://user-images.githubusercontent.com/116446650/206868235-175837f6-b523-4135-868a-fe20fd508f1e.png)

-Graveyard Labyrinth
(affected scenes: "Thanks, Kairi", "A Replica For Namine", "Final Confrontations II", "To Sperate Battles", "From Chains To Bonds", "Past Redux: To Sperate Battles", and "Terra's Heart")
![image](https://user-images.githubusercontent.com/116446650/206868258-e15eb303-29c5-4e9a-9720-b346b99b58d8.png)
![image](https://user-images.githubusercontent.com/116446650/206868382-2e4a4820-4284-441a-ab74-4eb686d29c16.png)

-He's A Pirate (which is also triplicated)
(affected scenes: "The Undead Pirates", "The Moonlight's Secret", "Elizabeth and Will", "Captain Jack Sparrow", "Attack On The Interceptor", "The Jack Sparrow Way", and "Into The Ocean")
![image](https://user-images.githubusercontent.com/116446650/206868408-251f5da5-e463-4f9f-b25e-5208664c5902.png)
![image](https://user-images.githubusercontent.com/116446650/206868469-92c4f328-0169-40e4-8211-acaebb5ede60.png)

-Road To A Hero
(affected scenes: "The Heart That Beats Inside", "To The Opera", "All for One", "A Medal!", and "Upgraded")
![image](https://user-images.githubusercontent.com/116446650/206868493-7955b38a-d5ea-4284-a99e-1e0e79665de2.png)
![image](https://user-images.githubusercontent.com/116446650/206868558-24a0e119-b728-4546-87de-ba90199781dc.png)

-Time to Shugyo
(affected scene: "Finding and Edge")
![image](https://user-images.githubusercontent.com/116446650/206868598-5136d20b-6e41-4c5f-87a9-b6c1d240a516.png)
![image](https://user-images.githubusercontent.com/116446650/206868628-47a46e36-b748-486b-a085-f013c908be21.png)

-Under The Sea
(affected scenes: "Under The Sea", "King Triton", and "Score 3: Under The Sea")
![image](https://user-images.githubusercontent.com/116446650/206868670-31f85970-cc71-467e-a54c-17ee3882b276.png)
![image](https://user-images.githubusercontent.com/116446650/206868683-9525e9f9-ecf8-41a4-b036-897caa1f54d0.png)

-and finally Unforgettable
(affected scenes: "Brought Together (Terra)", "Walls Of The Heart (Terra)", "The Lost Boys in Peril", "A Swarm Of Unversed", "The Wicked Wood Spirit", "Brought Together (Ventus)", "Walls Of The Heart (Ventus)", "An Important Match", "To Save A Friend", "Brought Together (Aqua)", "Walls Of The Heart (Aqua)", and "An Ace Up Randel's Sleeve".
![image](https://user-images.githubusercontent.com/116446650/206868757-29bfa7e3-48af-4b30-882f-98bf834ebf99.png)
![image](https://user-images.githubusercontent.com/116446650/206868878-02b5a6af-9b05-419b-bc05-a93429ea7392.png)

**Comment by WaterKH** [comment]
Amazing work! Thank you so much!
