### ISSUE TITLE
Add Alias/AppearAs Columns/Table [FEATURE REQUEST]

### ISSUE THREAD

**Issue by Bha-Gu** [WaterKH/WayfinderProjectAPI#9]
**Is your feature request related to a problem? Please describe.**
Luxu seems to track Xigbar so why Lea doesnot track Axel

**Describe the solution you'd like**
Add a toggle if we want to see character with multiple name as same or diffrent

**Describe alternatives you've considered**
Change the behavier one way or the other

**Additional context**
![Screenshot from 2022-10-22 07-25-23](https://user-images.githubusercontent.com/67630917/197313044-5603a749-35e8-4985-b513-934a229d03d4.png)

![Screenshot from 2022-10-22 07-32-23](https://user-images.githubusercontent.com/67630917/197313140-cd2c6a04-8901-4634-9b89-edc76abbdb81.png)

**Comment by Bha-Gu** [comment]
Luxu seems to track Xigbar so why Lea doesnot track Axel

**Comment by Bha-Gu** [comment]
![image](https://user-images.githubusercontent.com/67630917/197311421-d57dbc6f-bd0a-4839-97c1-5e8cd312cbda.png)

**Comment by Bha-Gu** [comment]
Searching luxu and ventus together seems to be buggy
Sorry i don't fully know how to use Github issues

**Comment by WaterKH** [comment]
No worries! This is a good question and I can add a table in potentially to account for aliases and people that appear as others

**Comment by WaterKH** [comment]
Make a new table, 2 columns (1 original, 2 appear as), when looking up person, include the other person as well

**Comment by WaterKH** [comment]
Add a Search Setting for this to see if we want to hit this table first

**Comment by WaterKH** [comment]
Closed by commit 956c9cc68d3d6ee107c7d6e907333a0ee253d061
